baseURL = "https://deteritus.com/"
languageCode = "pt"
title = "Deteritus"
theme = "deteritus"

[author]
  name = "Tiago Jacinto"

[taxonomies]
  tag = "tags"

[params]
  description = "Um blogue pessoal de Tiago Jacinto"
  author = "Tiago Jacinto"
  mastodon = "https://mastodon.social/@tiagojct"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10

[permalinks]
  [permalinks.page]
    blog = "/:slug/"
